### ISSUE TITLE
heroku app is failing on rpy.xyz

### ISSUE THREAD

**Issue by esonderegger** [benbalter/site-inspector-demo#1]
It responds with "invalid domain"

At first I thought this was caused by "xyz" being a relatively recent tld.
Then I cloned this repository, ran the app locally, and it worked!
I thought "perhaps the heroku version is running an old version of publicsuffix-ruby?", but no... the heroku app works for gen.xyz

Now I'm stumped. Perhaps this has something to do with the way I have cloudflare set up for rpy.xyz and it's unreachable from heroku's network?

Anyway, I thought you'd like to know. Thanks for all the work you're doing with this effort!

**Comment by konklone** [comment]
Was this meant for the [`site-inspector`](https://github.com/benbalter/site-inspector-ruby) Ruby lib and CLI tool?

**Comment by esonderegger** [comment]
Thanks for asking! And... maybe? The site-inspector CLI tool works correctly for rpy.xyz and all of its subdomains. But so does the sinatra app when I run it locally. I suspect the issue lies somewhere with how the sinatra app is deployed, which may well be which version of the ruby library it is using.

That said, I haven't been able to find any other valid domains for which the heroku app replies with "invalid domain", so my domain is probably quite an edge case. I plan on doing more testing to see if I can recreate the problem with another domain. Anyway, since this tool is designed for testing .gov domains, it's probably not worth worrying about.

**Comment by benbalter** [comment]
There's [a major refresh](https://github.com/benbalter/site-inspector-ruby/pull/31) in the works, which I hope to be able to deploy to the demo server soon, which should hopefully resolve the issue.

**Comment by esonderegger** [comment]
Very cool! I'd love to help test when it's ready.

**Comment by benbalter** [comment]
[Fixed](https://site-inspector.herokuapp.com/domains/rpy.xyz)
